### ISSUE TITLE
Consider a name change?

### ISSUE THREAD

**Issue by technosophos** [nornir-automation/nornir#136]
Hi, I'm one of the maintainers of another project named Brigade (https://brigade.sh, https://github.com/azure/brigade/) that might be similar enough to yours that it may cause some confusion. I read an article on your framework, which I think looks very cool. But I am a little worried that the similarity of our project names might confuse our users, especially since ours is also an automation tool (though specific to Kubernetes).

I thought I would raise the issue with you so that we can together do what's best for the broader community.

**Comment by dbarrosop** [comment]
Hi,
thanks for raising this issue. This collision is unfortunate but there are so many projects nowadays it's nearly impossible to come up with an original name :P Also, we decided this name more than a year ago as this gist can testity (https://gist.github.com/dbarrosop/9830a04d365d9098c948db32b5752e2c) and the name seemed available back then (although we had no code back then and the current project looks very little like to what we were describing there). I am not trying to start a war on who named the project first (you can probably claim that the project started internally even way back), just giving you some context to explain why the collision happened.

Back on topic. We are a small group of people doing this mostly for fun and because it's useful for our $DAYJOBS. This is not backed by any megacorporation or startup trying to monetize this project. What I am trying to say is that we have put a lot of effort in spreading the word and changing the name is quite a blow as our resources are extremely limited and that's not even counting the effort that would take to rename everything and making sure people is aware :(

We will discuss this internally and decide what to do, however, we had a quick chat and our initial impression was that the scope was different enough that given our resources it wasn't worth changing. I'd propose you the same, to change the name of your project but I guess you will play the card that you have more stars and your repo is older so I am not even going to bother :P

If you have any other suggestion to avoid confusions (add clarifications notes in the README maybe pointing at each other?) that might be less time consuming than changing the name I am sure that'd be easier on our end and we are very much open to anything that helps both projects and the community.

Thanks again for raising the issue
David

**Comment by dbarrosop** [comment]
Well, it's done. We are now nornir. Thanks again for reporting this :)

Closing this, feel free to reopen if you feel there is something to be done at this point and if you feel like tweeting or whatever we won't complain ;)

P.S: Fan of glide here btw :P

**Comment by karlrabe** [comment]
Nornir now competes in naming with this project on Github.
https://danieledesensi.github.io/nornir/description.html

**Comment by ktbyers** [comment]
@karlrabe Yes, it is pretty much impossible to not have some name overlap. Our project and the one you referenced are not similar.


Kirk
