### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by electricOzone** [nornir-automation/nornir#248]
When running a task such as `get_facts` on a large number of devices (over 5,000 in this case), napalm/paramiko begin throwing `OSError: [Errno 24] Too many open files` after the system's ulimit for open file descriptors is reached.

I'm not sure if the network sockets should be closed after a task is completed (since additional tasks could use existing connections), but in this case, the number of open network sockets is causing an issue.

I can provide additional information/testing as requested.

**Comment by ktbyers** [comment]
network tasks are by design kept open. You can manually close them if you choose in Nornir 2.X (I don't remember whether you can do this in Nornir 1.1 or not).

I think fundamentally you would either need to:
1. Increase your ulimit so that you didn't hit this limit.
2. Structure your program so you didn't hit this limit. Which might including closing connections.

Item 1 is probably the easier of the two to do.

**Comment by electricOzone** [comment]
Thanks for the info. For now, we will increase the ulimit. I'll look forward to trying out this feature in 2.X.
