### ISSUE TITLE
migrate to poetry or similar

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#287]
should we start using poetry or something else to manage dependencies?

@ktbyers @dmfigol

**Comment by dmfigol** [comment]
I've been migrating more and more of my projects to poetry and I really like it, my user experience has definitely improved and is consistent across libraries/applications.
I can work on this migration.
Since it changes the development workflow, every maintainer needs to be on-board with this change before this work has started.

**Comment by dbarrosop** [comment]
I am good with the change. Releasing nornir 2.0.0 was a bit of a pain in the ass because both pydantic and sphinx did some minor changes that were backwards incompatible so I want to start pinning libraries (although the lack of semver in python projects like pydantic is going to make this only a partial success).

**Comment by ktbyers** [comment]
I haven't used Poetry, but it looks very interesting so sounds good to me.

**Comment by dbarrosop** [comment]
Fixed via #315
