### ISSUE TITLE
[FEATURE REQUEST] When using netbox inventory plugin, ability to filter based on device tags.

### ISSUE THREAD

**Issue by Lewis-Goulden** [nornir-automation/nornir#433]
For me this would greatly improve the inventory plugin. 

Device groups could potentially be used, and potentially work as follows:

- Within Netbox assigning device tag of 'testing-device' to device 'switch-a' would allow you to filter group 'testing-device' and return 'switch-a'

I have checked the required data is returned via the Netbox API calls used by the Netbox inventory plugin.

**Comment by dbarrosop** [comment]
That sounds useful so wouldn't mind seeing a PR coming :)

**Comment by ktbyers** [comment]
It sounds like this is pretty easy to do with a transform_function (@carlmontanari did a proof-of-concept on it).

Also since it is getting added to data you can already filter on it.

Not that it wouldn't be nice to have this potentially transformed into groups, but there are existing ways to take advantage of it (also).

**Comment by Sumico** [comment]
Is the idea to use it to filter like this?
 `nr.filter(tags=["tag1", "tag2"])`

If not, it looks like you can filter on tags when you initialize Nornir using filter_parameters.

**Comment by dbarrosop** [comment]
Ok, I think I initially misunderstood the issue and thought the filler was meant to be server-side. The F object and transform functions should already be able to do this on the nornir side.

Closing this, feel free  to reopen or comment if you think there is anything to be done or to discuss

**Comment by ciscoshizzel** [comment]
Hi,

I seem to have an issue with filtering based on tags using Netbox and Nornir.
Using https://github.com/wvandeun/nornir_netbox --> NetBoxInventory2 provides a lot of data in the form of dicts, including tags which I am interested in. The problem is however that I am unable to use the nr.filter(tags=) option since NetBoxInventory2 provides an entire dict as shown below.

tags [{'id': 2, 'url': 'https://10.10.10.10/api/extras/tags/2/', 'name': 'OSPF', 'slug': 'ospf', 'color': '9e9e9e'}, {'id': 1, 'url': 'https://10.10.10.10/api/extras/tags/1/', 'name': 'Provisioning', 'slug': 'provisioning', 'color': '9e9e9e'}]

The only way to 'filter' seems to be to put the entire list as shown above in the filter option. This is however not what I am looking for.. I would like to filter my devices based on if they have the tag 'Provisioning'.

The NBInventory plugin also does not solve the problem since it only provides this data:

serial
vendor
asset_tag
site
role
model

Can you please help me?

I would love to use Netbox as my single source of truth with Nornir.

**Comment by NetIgo** [comment]
You can get it done by using the 'filter_func' option, as said above.
From my experince it's not that bad.
