### ISSUE TITLE
Update pydantic to 1.0

### ISSUE THREAD

**Issue by dmfigol** [nornir-automation/nornir#447]
Finally a major release of pydantic is out https://github.com/samuelcolvin/pydantic/releases
It would be great to finally pin the last dependency to a major version
Related to #428

**Comment by dbarrosop** [comment]
Sounds good to me. Is this something you will be looking into?

**Comment by AchilleAsh** [comment]
Hi,

I have a project using Pydantic 1.1 and I'm trying to plug Nornir in it so I upgraded its pydantic dep version to see if any issue rises.
It looks like the only issue (so far) is with the configuration parameters doc build with sphinx:

The ```.schema()``` method of pydantic ```BaseSetting``` now generates a different output that is more JSON Schema compliant than previsouly and uses _$ref_ keys that reference definitions ( as explained here https://json-schema.org/understanding-json-schema/structuring.html#reuse )
That's why ```docs/_data_templates/configuration-parameters.j2``` does not work anymore: the macro is expecting a _properties_ key inside _properties_ schema and the new schema only references a definition that have _properties_, using _$ref_ key.

Also note that ```Schema``` is deprecated and replaced by ```Field``` (drop-in replacement)


I'm willing to open a PR to fix this, but I'm confused by the contributing.rst: should I open one PR that bumps the pydantic version and another one that fixes the sphinx build, or a single one with both?

**Comment by dbarrosop** [comment]
One PR should be fine as technically you are fixing the test due to the version bump.
