### ISSUE TITLE
netmiko enable() should be configurable

### ISSUE THREAD

**Issue by Eising** [nornir-automation/nornir#451]
Hi,

I've run in to an issue where my routers cannot be configured with netmiko due to the enable() function run in `networking.netmiko_send_config`

In my particular case, I'm configuring Alcatel SROS devices that do not have a dedicated enable (`admin`) password configured, thus failing because of this with the following:
```
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

May I suggest you make this configurable some how? As a workaround I've made my own netmiko_send_config function with just the line referenced below commented out.

The problematic line is this:
https://github.com/nornir-automation/nornir/blob/f5a51269f8faffa3f078d14cadd81695419bfa76/nornir/plugins/tasks/networking/netmiko_send_config.py#L25

Thank you!

**Comment by ktbyers** [comment]
I think the Nornir-Netmiko behavior is correct i.e. `enable()` method should always be called/invoked prior to configuration mode. The expected behavior is that `enable-mode` is a requirement of going into `config-mode` (basically since the vast majority of platforms follow this pattern).

The issue is really in the Netmiko-SROS driver--this issue gets fixed/goes away in this PR:

https://github.com/ktbyers/netmiko/pull/1442

Alternatively, you can create a custom-task in Nornir.

**Comment by hellt** [comment]
@Eising in the next netmiko release we will have a new Nokia SR OS driver that should handle this situation

**Comment by balkandude** [comment]
I'm sorry if i'm posting at the wrong place but has this issue been solved? I'm running Nornir 3.0.0 with nornir_netmiko and getting error about enable()

**Comment by hellt** [comment]
@balkandude yes, recent netmiko should have enable functionality for Nokia SR OS

**Comment by akarneliuk** [comment]
Hello folks,

not sure it is. Here is my script:
```python
from nornir import InitNornir
from nornir.core.task import Result, Task
from nornir_netmiko import netmiko_send_command, netmiko_send_config

def config_device(task: Task) -> Result:
    """
    This task aims to demo the configuration of the network elements.
    """
    config_commands = []
    if task.host.platform == 'nokia_sros':
        for ife in task.host['interfaces']:
            temp_conf = f'router\n interface {ife["name"]}\n address {ife["ipv4"]}\n no shutdown'
            config_commands.extend(temp_conf.split('\n'))

    r3 = nr.run(task=netmiko_send_config, config_commands=config_commands)

    if task.host.name in nr.data.failed_hosts:
        task.host['task_3'] = False
    
    else:
        task.host['task_3'] = True

    return Result(host=task.host, result=task.host['task_3'])

# Body
if __name__ == "__main__":
    nr = InitNornir(config_file='config.yaml')
    test_3_results = nr.run(task=config_device)
```

Once I execute, I see the following error in the log:
```
2020-10-10 16:13:22,686 -  nornir.core -     INFO -        run() - Running task 'check_ssh' with args {} on 1 hosts
2020-10-10 16:13:22,687 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show chassis'} on 1 hosts
2020-10-10 16:13:28,081 -  nornir.core -     INFO -        run() - Running task 'save_config' with args {'bfd': 'config_backups'} on 1 hosts
2020-10-10 16:13:28,082 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'admin display', 'enable': False} on 1 hosts
2020-10-10 16:13:29,005 -  nornir.core -     INFO -        run() - Running task 'config_device' with args {} on 1 hosts
2020-10-10 16:13:29,005 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_config' with args {'config_commands': ['configure', 'router', ' interface system', ' address 3.3.3.3/32', ' no shutdown']} on 1 hosts
2020-10-10 16:13:29,453 - nornir.core.task -    ERROR -      start() - Host 'SR1': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 25, in netmiko_send_config
    net_connect.enable()
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/nokia/nokia_sros_ssh.py", line 87, in enable
    return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1674, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

Meanwhile,  `netmiko_send_command` works perfectly.

Cheers,
Anton

**Comment by hellt** [comment]
@balkandude @akarneliuk 
Please check that you have netmiko >3.3.0

**Comment by abudilov** [comment]
@hellt

I am seeing this issue in 3.3.0 paired with Nornir. 

Should I open a new issue?

```
2021-01-05 12:40:16,870 - nornir.core.task -    ERROR -      start() - Host 'sr.sv5': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/abudilovskiy/Documents/keymaker/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/abudilovskiy/Documents/keymaker/venv/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 25, in netmiko_send_config
    net_connect.enable()
  File "/Users/abudilovskiy/Documents/keymaker/venv/lib/python3.9/site-packages/netmiko/nokia/nokia_sros_ssh.py", line 87, in enable
    return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/Users/abudilovskiy/Documents/keymaker/venv/lib/python3.9/site-packages/netmiko/base_connection.py", line 1632, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```

**Comment by ktbyers** [comment]
@abudilov Are you passing in a `secret` to ConnectHandler?

Also are you using MD-CLI or legacy CLI on SR-OS?


Kirk

**Comment by abudilov** [comment]
@ktbyers I am using the Classic CLI. I tried passing the ```secret``` to the handler via the Nornir inventory. It only works if I add ```configure enable-admin``` and set ```admin-password```on the device. 
It is not a viable option as I'd have to pre-configure this on 1000+ devices.

I think the issue is in the Nornir code as it expects [enable](https://github.com/ktbyers/nornir_netmiko/blob/b187a978ca5939a026bf16b31b2d0a0cdc695f83/nornir_netmiko/tasks/netmiko_send_config.py#L25) for all vendors and Nokia Classic CLI doesn't have it configured by default. 

With netmiko_send_command it is not a problem since the [argument is set to false by default](https://github.com/ktbyers/nornir_netmiko/blob/b187a978ca5939a026bf16b31b2d0a0cdc695f83/nornir_netmiko/tasks/netmiko_send_command.py#L10)

**Comment by hellt** [comment]
Yes, that's the reason
The md-cli also doesnt have admin privileges enabled by default, so the
assumption from Nornir should be the aligned with netmiko - no enable is
needed by default unless "secret" is set

**Comment by abudilov** [comment]
@hellt not everyone in the field is at the sw version that supports or has MD-CLI enabled ;) wouldn't be using netmiko otherwise. 
@ktbyers I got my use case to work with issuing multiple netmiko_send_command, but it would be great if there was a way to pass enable=False to netmiko_send_config as well. Let me know if I should open an issue under nornir_netmiko project. Thanks!

**Comment by ktbyers** [comment]
Note, you can always create your own direct Nornir-netmiko task so if the pre-built one doesn't work for you, then this is the workaround which is pretty easy.

https://github.com/twin-bridges/nornir_course/blob/master/bonus1/collateral/netmiko_direct_task/netmiko_direct.py#L6

Unfortunately, the SR-OS behavior here is fairly odd relative to most other network platforms. I would argue the behavior is still really a bug in the Netmiko SR-OS driver (if I am understanding the issue correctly...it is possible that I am not understanding it, however). Netmiko behavior expections are--you must `always` be in enable mode to go into config mode.  If the device doesn't support this pattern, then Netmiko's driver behavior should be adjusted to accommodate this behavior expectation.

I am open to adding an argument, however (i.e. `enable=True` which you can then override via arguments)...but I still think it is fundamentally a bug in the Netmiko SR-OS driver (though I am not sure of how to work around it).

**Comment by hellt** [comment]
Hi guys,
sorry I didn't look at the code yesterday, but Nokia SR OS shouldn't error in a plain netmiko setup, nor should it require `secret` to be set if its not needed

https://github.com/ktbyers/netmiko/blob/develop/netmiko/nokia/nokia_sros_ssh.py#L89

here I remember @ktbyers and me created the function to detect if enabling should trigger the `enable` command based on the fact if the admin privileges were configured on the box.

So I am pretty confident that (if nothing changed in netmiko sros after that) if you try netmiko right now, then enable mode will be gracefully handled

**Comment by ktbyers** [comment]
I think it is because we have two different types of classical CLI users: those that have `configure enable-admin` configured and those that don't.

If we make Netmiko operate one way, we break one set of users. If we choose the other way, we break the other set of users. And basically we end up with one set of users that are annoyed at us over our choices.

**Comment by hellt** [comment]
Sorry, I don't get it or I forgot how it all worked.

Afair the code is intelligent enough to detect if enable mode needs to be
enabled, which should suite all sorts of users

How are we cutting off someone?

**Comment by ktbyers** [comment]
Relevant code is here:

```python
    def enable(self, cmd="enable", pattern="ssword", re_flags=re.IGNORECASE):
        """Enable SR OS administrative mode"""
        if "@" not in self.base_prompt:
            cmd = "enable-admin"
        return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
```

So if we are in classical CLI mode we always execute `enable-admin` on a Netmiko `enable()`. Some set of SR-OS users do not have `enable-admin` configured and consequently the above Nornir-Netmiko operations fail for them (since Nornir-Netmiko for config `always` calls `enable()`).

Let me know if I am misunderstanding something here, but that is my understanding of what is going on.

**Comment by abudilov** [comment]
@ktbyers I think your understanding is correct. While I am not an SROS guru by any means, prior to this I'd never seen the "enable-admin" nor needed to use it. Typically a user profile is configured with the required contexts and a default "admin" user already has "admin" context. This seems to be an equivalent of "sudo su" and I don't think netmiko should really bother with escalating the privileges like that. If the user passed to the ConnectHandler doesn't have the context permissions, an error can be raised.

**Comment by ktbyers** [comment]
Yes, we have had a different set of SR-OS users complain about `enable` not supporting `enabling-admin` (IIRC).

**Comment by hellt** [comment]
@ktbyers 
> Let me know if I am misunderstanding something here, but that is my understanding of what is going on.

I think its not like that

Nokia SR OS `enable()` just sets the enable command to the relevant CLI command based on SR OS mode (MD vs Classic), then this function calls base connection `enable()` method:
https://github.com/ktbyers/netmiko/blob/753cb53aca7692e8e67d3386b7614788f2b34d06/netmiko/nokia/nokia_sros_ssh.py#L83-L87

in base connection we first check check if we actually allowed to perform enable procedure

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1674

this is done by verifying what is returned by SR OS to the `enable/enable-admin` command:

https://github.com/ktbyers/netmiko/blob/753cb53aca7692e8e67d3386b7614788f2b34d06/netmiko/nokia/nokia_sros_ssh.py#L89-L99

So IMHO (and I remember testing these modes) there is no way a user will end up in a situation where enable is called when its not configure. Let me please know if this flow is not correct.

**Comment by ktbyers** [comment]
@hellt Let me double check some more.

**Comment by hellt** [comment]
sorry @ktbyers for unnecessarily eating your time 

My memory failed me and the current code is indeed seems to assume that enable must happen on SR OS regardless if it is configured or not.

`check_enable` method only checks if the SR OS node is in admin mode, but if it is not it doesn't mean it has enable mode configured, that leads to the issue in the `super.enable()` https://github.com/ktbyers/netmiko/blob/8bbe607a8fbf2a00deeefe2fa7f17c918792949d/netmiko/nokia/nokia_sros_ssh.py#L89-L99


I think the code of nokia.enable() might be enhanced to first detect if admin mode is configured on the device and only if it is, it must go through the `super.enable()` routine.

Now I recall why that was not an issue with bare netmiko - because in bare netmiko a user decides if he needs to call enable() and user knows if this mode is configured on the device upfront.

So I see two possible solutions:
1) make nornir-netmiko plugin less opinionated on the need of enable()
2) or enhance nokia.enable() to check if the enable mode is configured on the device, if it is - perform enable. If it doesn't - pass the function.

**Comment by ktbyers** [comment]
So let's do this--near term fix it in Nornir by adding an argument. Longer term potentially fix in Netmiko to allow some way to avoid this issue.

I will create an issue in Netmiko to track the longer term issue.

I am worried that we will just run into this problem elsewhere where Netmiko + other tool is being used (which is why the longer term fix is probably a good idea).

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/issues/2104
