### ISSUE TITLE
Fresh install issue - Incompatibility between napalm et netmiko?

### ISSUE THREAD

**Issue by ericorain** [nornir-automation/nornir#495]
Hi,

I have just installed python in 2.8.2, then updated pip and after that I installed nornir using the following command: "pip install nornir".

During installation I saw that message:

######################################

[...]

Collecting pycparser
  Downloading pycparser-2.19.tar.gz (158 kB)
     |████████████████████████████████| 158 kB ...
**ERROR: napalm 2.5.0 has requirement netmiko==2.4.2, but you'll have netmiko 3.0.0 which is incompatible.**
Installing collected packages: pyserial, pycparser, cffi, pynacl, cryptography, bcrypt, paramiko, lxml, pyYAML, ncclient, netaddr, scp, MarkupSafe, jinja2, junos-eznc, future, textfsm, netmiko, dnspython, passlib, ciscoconfparse, idna, certifi, urllib3, chardet, requests, nxapi-plumbing, pyeapi, pyIOSXR, napalm, typing-extensions, ruamel.yaml.clib, ruamel.yaml, mypy-extensions, nornir
    Running setup.py install for pycparser ... done

[...]

######################################

I do not know if it is a real problem or not between netmiko and napalm but it is still an error displayed to users.

**Comment by dmfigol** [comment]
@ericorain in the latest nornir version we have netmiko >= 3.0 as dependency but napalm has hard-pin of netmiko lower version. This is fixed in napalm already: https://github.com/napalm-automation/napalm/pull/1116
so the warning should go away once the new version of napalm is published.
not an issue with nornir, I am closing this.
