### ISSUE TITLE
adapt ansible plugin to nornir 3.0.0

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/nornir#509]
Relates to #486 and #504 

Adapt plugin to nornir 3.0.0.

For reference look at https://github.com/nornir-automation/nornir_napalm.

Don't forget to add details to the plugin repository. You can do so by adding it [here](https://github.com/nornir-automation/nornir.tech.src/blob/master/data/nornir/plugins.yaml)

If you have any questions don't hesitate to ask.

**Comment by dbarrosop** [comment]
@carlmontanari

**Comment by carlmontanari** [comment]
First draft: https://github.com/carlmontanari/nornir_ansible

Not sure if we had planned to tweak how any of the inventory things work but a quick check through the 3.0.0 branch didn't look like it (v possible I missed something obvious though!). This is working with 2.4.0 and should work with 3.x+ I suspect. Just rolled w/ requirements.txt for now to get rolling quickly since I'm a poetry noob, but can convert over if y'all care. Other than no poetry, tried to copy the napalm plugin so it should at least be a close approximation to what we want!

Lemme know if there is anything wonky with it and I can get it tuned up!

**Comment by dbarrosop** [comment]
Awesome! I will probably want to use for inventory plugins the same pattern I introduced to register connection plugins but that should require very small changes to what you already did. I will keep you posted.

**Comment by carlmontanari** [comment]
Better draft ready [here](https://github.com/carlmontanari/nornir_ansible) :)

Registration is working and such now. Pinned to 3.0.0.a2 for now. No docs still... one thing at a time I suppose :) but its working nicely w/ 3.0.0a2 in my testing so far!
