### ISSUE TITLE
possibility to catch Exceptions of underlying code

### ISSUE THREAD

**Issue by berahtlv** [nornir-automation/nornir#579]
Introduce possibility to catch Exceptions of underlying code with all Tracebacks.
At the moment even with "raise_on_error" Tracebacks from paramiko are shown (like paramiko.ssh_exception.SSHException).

Seems that Processors also can not catch that, at least I haven't managed to do that.
Nornir logging is disabled to write custom log messages.

**Comment by dbarrosop** [comment]
All the errors returned by tasks are available to the user, including inside processors. Look at the `Result` object as it holds all the information you need.

The exception available is going to be whatever the task raises, if the task is capturing an exception and raising another one there isn’t much that nornir can do though.

I am closing this because **I think** there isn’t nothing to do but if you have any particular example of something that doesn’t work feel free to comment/reopen.

Thanks!
