### ISSUE TITLE
(Windows) Fresh install of Nornir 2.5.0 error: ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by shmoeshmeps** [nornir-automation/nornir#586]
Created a new venv with Python 3.8 in Pycharm on Windows.

Ran:
`pip install nornir`

Created base script
```
from nornir import InitNornir

nr = InitNornir()
```

Get error back:
```
....(abbreviated)....
  File "C:\Users\jshep\PycharmProjects\nornir_intro\venv2\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'fcntl'
```

If (in the same venv) I then install
`pip install nornir==2.4.0`

I run it and get the expected
`FileNotFoundError: [Errno 2] No such file or directory: 'hosts.yaml'`

I can then revert back to 2.5.0:
`pip install nornir==2.5.0`
and the fcntl error no longer appears.

**Comment by ktbyers** [comment]
The `fcntl` issue is ultimately because TextFSM doesn't work on Windows. If you install this branch that should fix your issue:

https://github.com/google/textfsm/pull/82

You should be using Nornir 2.5.0.


Regards,

Kirk

**Comment by shmoeshmeps** [comment]
Hi Kirk,

If this issue will affect anyone who tries to run the most recent stable 
version of Nornir (2.5.0)  in Windows are you not able to modify the 
version of textfsm pulled in your source code? I imagine it'll be quite 
off putting if new windows users hit an error (I'm showcasing it to my 
colleagues next week).

Cheers

Joe

**Comment by ktbyers** [comment]
It is not a Nornir issue. It happens on earlier versions of Nornir as well (not sure what happened in your case, but the `fcntl` issue has existed for a long, long time).

This is a TextFSM issue and indirectly a Juniper PyEZ issue (i.e. Juniper PyEZ is importing TextFSM and causes this breakage). 

Yeah, but maybe I will release a fixed version of TextFSM to pypi and/or submit a PR to Juniper PyEZ to more gracefully handle this.

Note, I have been fixing various versions of this TextFSM breakage for several years now. Nornir is not even using TextFSM directly (it is just that PyEZ decided to import it which then caused other people to break when using PyEZ on Windows).

There are other fixes:

1. Install a downrev version of Juniper PyEZ is probably the easiest.

**Comment by dbarrosop** [comment]
nornir 3 doesn’t have this issue as it doesn’t depend on any dependencies that depend on pyez or textfsm

**Comment by bradh11** [comment]
I recently experienced this error with a new project too and ended up using raw netmiko because I didn’t have time to troubleshoot it.  It does present itself as a nornir  problem even though it’s a dependency buried deep.  Is there any chance you could add windows tests or add some error handler to more clearly state what to do to resolve the issue?   Glad to hear 3.0 will not have this problem.

**Comment by shmoeshmeps** [comment]
Indeed, this was my reason for raising it. It's not a Nornir issue, but it didn't happen in 2.4 and any windows users installing 2.5 will hit this issue and there's no documentation or hint on how to resolve it.

**Comment by ktbyers** [comment]
@bradh11 The fix is here:

https://github.com/google/textfsm/pull/82

I have also put fixes into Netmiko, and ntc-templates for this issue across time. But ultimately it needs fixed in the underlying TextFSM library.

Here is the behavior improvement I recently put into ntc-templates for it (this doesn't fix the underlying issue, but improves the behavior):

https://github.com/networktocode/ntc-templates/pull/803

The behavior improvement in ntc-templates should give a clearer indication of the error, but that new version still needs released to pypi and then after that an improvement needs made to Juniper's PyEZ library.

Note, while Nornir Core won't have this same issue, Nornir once you install the nornir_napalm plugin will.
