### ISSUE TITLE
Accessing Group Vars for ansible Inventory

### ISSUE THREAD

**Issue by parth995** [nornir-automation/nornir#701]
Hi Team,

I see a bug or challenge may be to access a group vars/items in nornir script when we use ansible as a inventory plugin.

**Below thing works :-**
nr.inventory.hosts['<host_name>'].items()

**Below one Doesn't works :-**
nr.inventory.groups['<group_name>'].items()

Any help would be appreciated. Thanks

**Comment by dmfigol** [comment]
this issue tracker is for problems with nornir core. issues with plugins could be reported in the appropriate plugin repository, e.g.
https://github.com/carlmontanari/nornir_ansible (I am not sure how actively that plugin is maintained)
that said, even if this issue was opened there, provided details are not enough to assist you. at the minimum, there needs to be minimal reproduction which demonstrates the problem together with versions of python/nornir/plugin.
closing this issue

**Comment by parth995** [comment]
**Versions of package used :-**
netmiko==3.4.0
nornir==3.1.1
nornir-ansible==2020.9.26
nornir-napalm==0.1.2
nornir-scrapli==2021.1.30
nornir-utils==0.1.2
Python 3.9.5
